export const USER_PROFILE_IMAGE_UPLOAD_REQUEST =
  'USER_PROFILE_IMAGE_UPLOAD_REQUEST';
export const USER_PROFILE_IMAGE_UPLOAD_SUCCESS =
  'USER_PROFILE_IMAGE_UPLOAD_SUCCESS';
export const USER_PROFILE_IMAGE_UPLOAD_FAILURE =
  'USER_PROFILE_IMAGE_UPLOAD_FAILURE';
